### PR TITLE
feat(draft): add `summaryCustomized` to draft & article;

### PR DESCRIPTION
**Pull request by robertu7**
Also add test cases for `putDraft` and `editArticle`;

### CODE REVIEW

**Review by guoliu — CHANGES_REQUESTED** [review]
Shall we just use `summary` in db schema and API, and overwrite this field when user input their summary? If we can treat the default summary and customized summary the same way, we can simplify the overall logic.

**Comment by robertu7** [comment]
> Shall we just use `summary` in db schema and API, and overwrite this field when user input their summary? If we can treat the default summary and customized summary the same way, we can simplify the overall logic.

We will be showing the summary in the article detail only if it's customized, relying on `summary` is hard to do that.

image

**Review by guoliu — APPROVED** [review]

**Comment by guoliu** [comment]
> > Shall we just use `summary` in db schema and API, and overwrite this field when user input their summary? If we can treat the default summary and customized summary the same way, we can simplify the overall logic.
> 
> We will be showing the summary in the article detail only if it's customized, relying on `summary` is hard to do that.
> 
> image

Sounds good, thanks for the explanation!

**Review by devformatters — APPROVED** [review]
Go. ✊🏻

**Pull request merged**
